CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702123242_InitialCreate') THEN
    CREATE TABLE "Customers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" text NOT NULL,
        "Email" text NOT NULL,
        "PhoneNumber" text NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "CreatedBy" text NOT NULL,
        "UpdatedDate" timestamp with time zone,
        "UpdatedBy" text,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702123242_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260702123242_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

